import { imageSrc, LIBRARY } from "./library";

/** Explicit subject cues, never a random photo from an interest. */
const HINTS: Record<string, string> = {};
function assign(image: string, ids: string) {
  for (const id of ids.split(" ")) HINTS[id] = image;
}
assign("salmon", "k-fattyfish e-fish f-fish l-salmon");
assign("legumes", "k-legumes v-fibres v-legum e-fibres f-fibres sq-mediterranee-r");
assign("hint-tension", "k-salt v-hta e-salt sq-tension-r");
assign("sq-sarcopenie", "k-protein v-sarco e-prot e-muscle");
assign("sq-microbiote", "k-fibres v-microb sq-microbiote-r sq-microbiote-f");
assign("hint-skeleton", "k-calcium");
assign("orange", "k-citrus v-antiox");
assign("sq-diabete", "v-glyc v-diab");
assign("hint-pancreas", "v-insul sq-diabete-r");
assign("hint-artery", "v-chol med-ev-arterio");
assign("water", "v-hydra e-water");
assign("hint-weight", "v-denut");
assign("eggs", "v-prot e-protage f-protein");
assign("vegetables", "v-micronut e-veg");
assign("yogurt", "v-calc sq-microbiote-e");
assign("olive_oil", "l-olive f-olive sq-mediterranee-f");
assign("lentils", "l-lentils");
assign("almonds", "l-almonds");
assign("broccoli", "l-broccoli");
assign("oats", "l-oats sq-diabete-e");
assign("balanced_meal", "e-med");
assign("sleep", "e-sleep");
assign("walk", "e-activity f-walk med-ex-autonomy spo-ex-age sq-sarcopenie-e sq-sarcopenie-f sq-marathon-e");
assign("breakfast_sweet", "e-breakfast");
assign("soda", "f-soda");
assign("monet", "sq-monet-r sq-monet-e sq-monet-f art-ex-impression");
assign("mona_lisa", "sq-renaissance-r sq-renaissance-e sq-renaissance-f art-ex-museum");
assign("sq-mediterranee", "sq-mediterranee-e");
assign("sq-sarcopenie", "sq-sarcopenie-r");
assign("walk", "sq-diabete-f");
assign("salt", "sq-tension-e");
assign("hint-tension", "sq-tension-f");
assign("sq-photosynthese", "sq-photosynthese-r sq-photosynthese-f");
assign("forest", "sq-photosynthese-e sci-ex-climate");
assign("hint-solstice", "sq-saisons-r");
assign("sq-saisons", "sq-saisons-e sq-saisons-f geo-ex-climate");
assign("hint-milk", "sq-pasteur-r");
assign("sq-pasteur", "sq-pasteur-e sq-pasteur-f med-ex-prevention");
assign("hint-gard", "sq-rome-r sq-rome-e");
assign("sq-rome", "sq-rome-f");
assign("sq-hugo", "sq-hugo-r sq-hugo-e sq-hugo-f lit-ex-reading");
assign("hint-staircase", "sq-loire-r");
assign("sq-loire", "sq-loire-e sq-loire-f");
assign("sq-abeilles", "sq-abeilles-r sq-abeilles-e sq-abeilles-f nat-ex-biodiv");
assign("hint-sailor", "sq-internet-r");
assign("sq-internet", "sq-internet-e sq-internet-f tec-ex-internet");
assign("hint-turmeric", "sq-epices-r");
assign("cooking", "sq-epices-e cui-ex-home");
assign("sq-epices", "sq-epices-f");
assign("sq-marathon", "sq-marathon-r sq-marathon-f spo-ev-endurance");
assign("sq-penicilline", "sq-penicilline-r sq-penicilline-e sq-penicilline-f sci-ex-method");
assign("sq-adn", "sq-adn-r sq-adn-e sq-adn-f");
assign("hint-mri", "sq-imagerie-r tec-ex-medtech");
assign("sq-imagerie", "sq-imagerie-e sq-imagerie-f");
assign("hint-clay", "sq-langage-r");
assign("book", "sq-langage-e sq-langage-f his-ex-print");
assign("hint-david", "sq-florence-r");
assign("sq-florence", "sq-florence-e sq-florence-f his-ex-renaissance");
assign("sq-venise", "sq-venise-r sq-venise-e sq-venise-f geo-ex-travel");
assign("sq-pompei", "sq-pompei-r sq-pompei-e sq-pompei-f");
assign("hint-cube", "sq-cubisme-r");
assign("sq-cubisme", "sq-cubisme-e sq-cubisme-f");
assign("hint-bowler", "sq-surrealisme-r");
assign("sq-surrealisme", "sq-surrealisme-e sq-surrealisme-f");
assign("hint-gravity", "sci-ev-gravity");
assign("hint-pyramids", "his-ev-pharaon");
assign("hint-fresco", "art-ev-fresque");
assign("hint-archipelago", "geo-ev-archipel");
assign("hint-marmot", "nat-ev-hiber");
assign("autumn", "nat-ex-seasons");
assign("hint-verse", "lit-ev-alexandrin lit-ex-fable");
assign("hint-satellite", "tec-ev-satellite");
assign("hint-stew", "cui-ev-mijoter cui-ex-share");
assign("football", "spo-ex-team");
assign("phone", "rp-ex-change");

export type VisualHint = { image: string; alt: string; caption?: string };
export function visualHintFor(item: { id: string; image?: string | null; options?: { image?: string }[] }): VisualHint | null {
  const image = HINTS[item.id] ?? item.image ?? item.options?.find((o) => o.image)?.image;
  if (!image || !imageSrc(image)) return null;
  if (item.id === "sq-microbiote-e") return { image, alt: "Un bol de yaourt nature, un lait fermenté", caption: "Yaourt nature · lait fermenté" };
  return { image, alt: LIBRARY.find((entry) => entry.id === image)?.label ?? "Indice visuel pour cette question" };
}